#!/bin/sh
# (C) by Filip M. Noetzel

SUBDIRECTORY_OK=Yes
OPTIONS_SPEC=

ref_overlook=refs/overlook

git rev-parse -q --verify $ref_overlook >/dev/null 2>/dev/null
HAVE_OVERLOOK=$?

if [ "$HAVE_OVERLOOK" -eq "0" ]; then
        . git-sh-setup &&
	cd_to_toplevel &&
	( git show $ref_overlook -p | patch --reverse > /dev/null ) || die "unapplying overlooked changes failed";
fi

git $@
RETURN=$?

if [ "$HAVE_OVERLOOK" -eq "0" ]; then
	( git show $ref_overlook -p | patch > /dev/null ) || die "unapplying overlooked changes failed"
fi

exit $RETURN
